name: translator_app
description: online translator
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gen: ^5.3.1
  flutter_gen_runner:
  easy_splash_screen: ^1.0.4
  html_unescape: ^2.0.0
  http: ^0.13.4
  translator: ^0.1.7
  speech_to_text: ^6.3.0
  highlight_text: ^1.4.0
  avatar_glow: ^2.0.2
  text_to_speech:
    path: E:\Programming\Mobile\Flutter\custom package\text_to_speech-main
  #intervalprogressbar: ^2.0.1
  google_ml_kit: ^0.7.3
  image_picker: ^0.8.5+3
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Irs
      fonts:
        - asset: assets/fonts/irs.ttf
